quiz:
    path:     /quiz/{id}
    defaults: { _controller: AppBundle\Controller\QuizController::quizAction, id: 1 }
    requirements:
      id: \d+
#quiz_ajax:
#  path:     /quizajax
#  defaults: { _controller: AppBundle\Controller\QuizController::quizAjaxAction }

front:
    path:     /
    defaults: { _controller: AppBundle\Controller\QuizController::frontAction }

test:
  path: /test
  defaults: {_controller: AppBundle\Controller\QuizController::testAction}

login:
  path:     /login
  defaults: {_controller: AppBundle\Controller\SecurityController::loginAction}

logout:
  path: /logout

create_quiz:
  path: /new/quiz
  defaults: {_controller: AppBundle\Controller\QuizController::newAction}

news_list:
  path: /news
  defaults: {_controller: AppBundle\Controller\NewsController::indexAction}

news:
  path: /news/{id}
  defaults: {_controller: AppBundle\Controller\NewsController::indexAction}

news_new:
  path: /new/news
  defaults: {_controller: AppBundle\Controller\NewsController::newAction}

duel_pessimistic:
  path: /duel_pessimistic
  controller: AppBundle\Controller\QuizController:assignDuelPessimistic2Action
  methods: POST

duel_optimistic:
  path: /duel_optimistic
  controller: AppBundle\Controller\QuizController:assignDuelOptimisticAction

duel_queue:
  path: /duel_queue
  controller: AppBundle\Controller\QuizController:assignDuelQueueAction