<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Duel;
use AppBundle\Entity\Quiz;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DuelRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Duel::class);
    }

    public function getCountDuelsForQuiz(Quiz $quiz)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->select('count(d.id)')
            ->where('d.quiz = :quiz')
            ->setParameter(':quiz',$quiz);

        return (int) $qb->getQuery()
            ->getSingleScalarResult();

    }

    public function customQueryPessimistic()
    {
        $qb = $this->createQueryBuilder('d');
        $qb->select('d')
            ->where('d.user2 is null')
            ->orderBy('d.id')
            ->setMaxResults(1);
        $query = $qb->getQuery();
        $query->setLockMode(\Doctrine\DBAL\LockMode::PESSIMISTIC_WRITE);

        return $query->getOneOrNullResult();
    }

    public function resetDuels()
    {
        $sql = "
            DELETE FROM duels D;
            ALTER TABLE `duels`
                AUTO_INCREMENT=1;
        ";
        $this->getEntityManager()->getConnection()->executeQuery($sql);
    }

    public function countPairedDuels()
    {
        $sql = "
            SELECT 
                COUNT(D.id) as total_duels,
                IFNULL(Q.assigned_duels,0) as assigned_duels,
                IFNULL(Q2.not_assigned_duels,0) as not_assigned_duels
            FROM duels D
            JOIN (
                SELECT 
                    COUNT(D.id) AS assigned_duels
                FROM duels D
                WHERE D.user_id_1 IS NOT NULL AND D.user_id_2 IS NOT NULL
            ) Q
            JOIN (
                SELECT
                    COUNT(D.id) AS not_assigned_duels
                FROM duels D
                WHERE D.user_id_2 IS NULL
            ) Q2
            ;
        ";
        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAssociative();
    }
}
