<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Duel;
use AppBundle\Entity\Quiz;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DuelRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Duel::class);
    }

    public function getCountDuelsForQuiz(Quiz $quiz)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->select('count(d.id)')
            ->where('d.quiz = :quiz')
            ->setParameter(':quiz',$quiz);

        return (int) $qb->getQuery()
            ->getSingleScalarResult();

    }
}
