<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Question;
use AppBundle\Entity\Quiz;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Persistence\ManagerRegistry;
use function Doctrine\ORM\QueryBuilder;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Question::class);
    }

    public function generateQuestionsForQuiz(int $amount, Quiz $quiz)
    {
        $qb = $this->createQueryBuilder('q');
        $qb->addSelect('q, RAND() as hidden rand')
            ->where($qb->expr()->eq('q.quiz',':quiz'))
            ->setParameter(':quiz', $quiz)
            ->orderBy('rand')
            ->setMaxResults($amount);

        return $qb->getQuery()->getResult();

    }
}
