<?php

namespace AppBundle\Entity\Repository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveQuizzes()
    {
        $qb = $this->createQueryBuilder('q');
        $qb -> where('q.status = 1')
            ->andWhere('CURRENT_TIMESTAMP() BETWEEN q.dateStart AND q.dateEnd');

        return $qb->getQuery()->getResult();
    }
}
