<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Quiz;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Quiz::class);
    }

    public function getActiveQuizzes()
    {
        $qb = $this->createQueryBuilder('q');
        $qb -> where('q.status = 1')
            ->andWhere('CURRENT_TIMESTAMP() BETWEEN q.dateStart AND q.dateEnd');

        return $qb->getQuery()->getResult();
    }
}
