<?php

namespace AppBundle\Entity\Repository;

use Doctrine\Common\Cache\ApcCache;
use Doctrine\Common\Cache\ApcuCache;
use Doctrine\ORM\Cache;
use Predis;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveQuizzes()
    {
        $client = new ApcuCache();

        if ($client->contains('activeQuizzes')) {
            return $client->fetch('activeQuizzes');
        }
        $qb = $this->createQueryBuilder('q');
        $qb -> where('q.status = 1')
            ->andWhere('CURRENT_TIMESTAMP() BETWEEN q.dateStart AND q.dateEnd');
        $result = $qb->getQuery()->getResult();
        $client->save('activeQuizzes', $result);
        return $result;
    }
}
