AppBundle\Entity\Duel:
    type: entity
    table: duels
    indexes:
        FK_answers_quizes:
            columns:
                - user_id_2
        FK_answers_questions:
            columns:
                - user_id_1
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        version:
            type: integer
            version: true
        result:
            type: integer
            nullable: true
        status:
            type: integer
            nullable: false
            options:
                default: 0
        quizKey:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: quiz_key
    manyToOne:
        user1:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_1:
                    referencedColumnName: id
            orphanRemoval: false
        user2:
            targetEntity: User
            nullable: true
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_2:
                    referencedColumnName: id
            orphanRemoval: false
        quiz:
            targetEntity: Quiz
            cascade: { }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                quiz_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        questions:
            targetEntity: AppBundle\Entity\DuelQuestion
            mappedBy: duel
    lifecycleCallbacks: {  }
