AppBundle\Entity\Quiz:
    type: entity
    table: quizes
    cache:
        usage: READ_ONLY
    repositoryClass: AppBundle\Entity\Repository\QuizRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
            options:
                default: '0'
        dateStart:
            type: datetime
            nullable: true
            column: date_start
        dateEnd:
            type: datetime
            nullable: true
            column: date_end
        tries:
            type: boolean
            nullable: true
    oneToMany:
        questions:
            targetEntity: AppBundle\Entity\Question
            cascade: [persist]
            mappedBy: quiz
    lifecycleCallbacks: {  }
