AppBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: AppBundle\Entity\Repository\UserRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        login:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        password:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        surname:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        email:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        answer:
            targetEntity: Answer
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: user_answer
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: answer_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
